---
version: 2
jobs:
####################################################################################################
## JOB:     setup-test-environment
## PURPOSE: Creates an RSA private key in a CircleCI workspace directory based on values from 
##          the environment variables that are available to this project.
####################################################################################################
  setup-test-environment:
    docker:
      - image: ncino/ci-sfdx-only
    steps:
      - run: 
          name: Display version info for the Salesforce CLI and core plugins (will force updates if needed)
          command: |
            sfdx version          # Output the version of the CLI
            sfdx plugins --core   # Output the version of the core plugins
      - run:
          name: Prepare all JWT Key Files that might be required by subsequent jobs
          command: |
            # Create directory where all JWT Org Keys will be stored
            mkdir /tmp/sfdx-keys
            # Convert the Hex Keys stored in the context's environment variables back to binary
            #echo $DEVHUB_SERVER_KEY_HEX | xxd -r -ps >> /tmp/sfdx-keys/dev-hub.key

            #sed 's/\([0-9A-F]\{2\}\)/\\\\\\x\1/gI' "$DEVHUB_SERVER_KEY_HEX" | xargs printf
            echo $DEVHUB_SERVER_KEY_HEX | busybox base64 -d  >> /tmp/sfdx-keys/dev-hub.key

            # Confirm that our converted keys are both valid RSA Private Keys
            openssl rsa -in /tmp/sfdx-keys/dev-hub.key -check -noout
      - run:
          name: Validate connection/authentication against the Dev Hub
          command: |
            # Confirm that the key can actually be used to login to the specific
            # Salesforce Org that the username stored in $DEVHUB_SFDC_USERNAME
            # is associated with.
            sfdx force:auth:jwt:grant --clientid $DEVHUB_CONSUMER_KEY \
                                      --jwtkeyfile /tmp/sfdx-keys/dev-hub.key \
                                      --username $DEVHUB_SFDC_USERNAME

      # Ensure that that the dev-hub.key file that was just created will be
      # available to other jobs performed during this build.
      - persist_to_workspace:
          root: /tmp/sfdx-keys
          paths:
            - dev-hub.key

      # Store SFDX logs as artifacts
      - store_artifacts:
          path: ~/.sfdx/sfdx.log
          destination: sfdx-logs

####################################################################################################
## JOB:     node-latest
## PURPOSE: ???
####################################################################################################
  node-latest: &test
    docker:
      - image: node:latest
    working_directory: ~/cli
    steps:
      - checkout
      - restore_cache: &restore_cache
          keys:
            - v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
            - v1-npm-{{checksum ".circleci/config.yml"}}
      - run:
          name: Install dependencies
          command: yarn
      - run:
          name: Testing
          command: yarn test
      - run:
          name: Submitting code coverage to codecov
          command: |
            ./node_modules/.bin/nyc report --reporter text-lcov > coverage.lcov
            curl -s https://codecov.io/bash | bash

####################################################################################################
## JOB:     node-8
## PURPOSE: ???
####################################################################################################
  node-8:
    <<: *test
    docker:
      - image: node:8
  cache:
    <<: *test
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: yarn
      - save_cache:
          key: v1-npm-{{checksum ".circleci/config.yml"}}-{{checksum "yarn.lock"}}
          paths:
            - ~/cli/node_modules
            - /usr/local/share/.cache/yarn
            - /usr/local/share/.config/yarn

####################################################################################################
## WORKFLOW:  SFDX-Falcon Plugin Tests
## PURPOSE:   Primary workflow used by the CI process.
####################################################################################################
workflows:
  version: 2
  "SFDX-Falcon Plugin Tests":
    jobs:
      - setup-test-environment:
          context: org-global
          filters:
            branches:
              only:
                - test-config


#      - node-latest
#      - node-8
#      - cache:
#          filters:
#            tags:
#              only: /^v.*/
#            branches:
#              ignore: /.*/
